name: Docker Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
       docker login
       docker build . --file Dockerfile --tag novcn/mediacat:$(cat VERSION)
       docker tag novcn/mediacat:$(cat VERSION) novcn/mediacat:latest
       docker push novcn/mediacat:$(cat VERSION)
       docker push novcn/mediacat:latest
